# Generated by Django 3.2.23 on 2024-01-02 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='time_destination',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='time_origin',
        ),
    ]
