# Generated by Django 3.2.23 on 2024-01-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20240102_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='img',
            field=models.ImageField(default='destination_images/no_img.jpg', upload_to='destination_images/'),
        ),
    ]
