# Generated by Django 3.2.2 on 2024-01-09 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_destination_city'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination_city',
            old_name='city_id',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='destination_city',
            old_name='destination_id',
            new_name='destination',
        ),
    ]
