# Generated by Django 3.2.23 on 2024-01-05 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_nationalcodes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='seat',
        ),
        migrations.AddField(
            model_name='nationalcodes',
            name='seat',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='nationalcodes',
            name='national_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
