# Generated by Django 3.2.2 on 2024-01-10 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20240110_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
